[project]
name = "ai-agent-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wanggang2", email = "wanggang2@yxt.wecom.work" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
ai-agent-course = "ai_agent_course:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
